# Generated by Django 4.1.1 on 2022-10-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commision",
            field=models.FloatField(default=0.1, editable=False, max_length=5),
        ),
    ]
