# Generated by Django 4.1.1 on 2022-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_amount',
            field=models.FloatField(default=0.01, max_length=5),
        ),
    ]
