# Generated by Django 4.1.1 on 2022-10-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_system", "0002_alter_transaction_commision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commision",
            field=models.FloatField(default=0.1, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transfer_amount",
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
