# Generated by Django 4.1.1 on 2022-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_system", "0003_alter_transaction_commision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commision",
            field=models.DecimalField(
                decimal_places=2, default=0.1, editable=False, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transfer_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
