# Generated by Django 4.1.1 on 2022-10-12 16:36

import bank_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0004_alter_transaction_transfer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_amount',
            field=models.FloatField(default=0.0, max_length=5, validators=[bank_system.models.Transaction.validate_transfer_amount]),
        ),
    ]
